### ISSUE TITLE
nonechucks breaks with pytorch's revision not in int

### ISSUE THREAD

**Issue by wakandan** [msamogh/nonechucks#21]
```
Traceback (most recent call last):
  File "<redacted>", line 24, in <module>
    import nonechucks as nc
  File "/usr/local/lib/python3.6/dist-packages/nonechucks/__init__.py", line 27, in <module>
    MAJOR, MINOR = _get_pytorch_version()
  File "/usr/local/lib/python3.6/dist-packages/nonechucks/__init__.py", line 12, in _get_pytorch_version
    major, minor, patch = [int(x) for x in version.split(".")]
  File "/usr/local/lib/python3.6/dist-packages/nonechucks/__init__.py", line 12, in <listcomp>
    major, minor, patch = [int(x) for x in version.split(".")]
ValueError: invalid literal for int() with base 10: '0+cu92'
root@842e18f1c34c:/<redacted># python
Python 3.6.7 (default, Oct 21 2018, 04:56:05)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.2.0+cu92'
>>>
```

**Comment by adamklec** [comment]
Just ran into this. I want to use nonechucks with the dev version of pytorch.
```
Traceback (most recent call last):
  File "/home/ubuntu/table-recognition/train.py", line 9, in <module>
    import nonechucks as nc
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/nonechucks/__init__.py", line 27, in <module>
    MAJOR, MINOR = _get_pytorch_version()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/nonechucks/__init__.py", line 12, in _get_pytorch_version
    major, minor, patch = [int(x) for x in version.split(".")]
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/nonechucks/__init__.py", line 12, in <listcomp>
    major, minor, patch = [int(x) for x in version.split(".")]
ValueError: invalid literal for int() with base 10: 'dev20200331+cu101'
```
